//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypozyczalniaSamochodow
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientTable()
        {
            this.OrdersTable = new HashSet<OrdersTable>();
        }
    
        public int idClient { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<long> PESEL { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersTable> OrdersTable { get; set; }
    }
}
