//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypozyczalniaSamochodow
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTable
    {
        public int idOrder { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public Nullable<System.DateTime> rentalTerm { get; set; }
        public Nullable<System.DateTime> returnTerm { get; set; }
        public Nullable<System.DateTime> returnDeadline { get; set; }
    
        public virtual EquipmentTable EquipmentTable { get; set; }
    }
}
