//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypozyczalniaSamochodow
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTable
    {
        public int idOrders { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<System.DateTime> rentalDate { get; set; }
        public Nullable<System.DateTime> returnTerm { get; set; }
        public Nullable<System.DateTime> returnDate { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<decimal> priceOfOrder { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual ClientTable ClientTable { get; set; }
        public virtual EquipmentTable EquipmentTable { get; set; }
    }
}
